const TREE_DELAY: Number = 15000;
const BOT_DELAY: Number = 1000;
const COLORS = {
	ICON_COLOR: "#FFFFFFAB",
	LINE_STROKE: "#FFFFFF56",
	TREE_NODE: "#34A0D3E1",
	NEW_NODE: "#34D376E1",
	BACKGROUND: "#121212FF",
	TEXT: "#FFFFFF",
	USER_BUBBLE: "#FFFFFF",
	SURFACE: "#2A2A2A",
	USER_TEXT: "#000000",
	PRIMARY: "#2A2A2A",
	FEINT_TEXT: "#b3b3b3",
	FEINT_LINES: "#b3b3b3",
	BORDER: "#FFFFFF",
};

const TREE_NODE = {
	HEIGHT: 40,
	WIDTH: 10,
	TEXT_COLOR: "#FFFFFF",
	SPREAD: 3.5,
};

const TREE_MAP = {
	CONTENT_WIDTH: 2000,
	CONTENT_HEIGHT: 1000,
	CONTAINER_WIDTH: 350,
	CONTAINER_HEIGHT: 500,
};

const ROOT_NODE_DATA = "Self-Improvement";

export { TREE_DELAY, COLORS, BOT_DELAY, TREE_NODE, ROOT_NODE_DATA, TREE_MAP };
